
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SampleClassification.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SampleClassification.ModelInput sampleData = new SampleClassification.ModelInput()
            {
                ID = @"71",
                Tanggal = @"17-Aug-20",
                Judul = @"Pemakaian Masker Menyebabkan Penyakit Legionnaires",
                Narasi = @"A caller to a radio talk show recently shared that his wife was hospitalized n told she had COVID n only a couple of days left to live . A doctor friend suggested she be tested for legionnaires disease because she wore the same mask every day all day long . Turns out it WAS legionnaires disease from the moisture n bacteria in her mask . She was given antibiotics n within two days was better . WHAT IF these ‘spikes’ in COVID are really something else due to ‘mask induced infections’ .??🤔🤔🤔",
                Nama_file_gambar = @"71.jpg",
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"ID: {@"71"}");
            Console.WriteLine($"Label: {@"1"}");
            Console.WriteLine($"Tanggal: {@"17-Aug-20"}");
            Console.WriteLine($"Judul: {@"Pemakaian Masker Menyebabkan Penyakit Legionnaires"}");
            Console.WriteLine($"Narasi: {@"A caller to a radio talk show recently shared that his wife was hospitalized n told she had COVID n only a couple of days left to live . A doctor friend suggested she be tested for legionnaires disease because she wore the same mask every day all day long . Turns out it WAS legionnaires disease from the moisture n bacteria in her mask . She was given antibiotics n within two days was better . WHAT IF these ‘spikes’ in COVID are really something else due to ‘mask induced infections’ .??🤔🤔🤔"}");
            Console.WriteLine($"Nama_file_gambar: {@"71.jpg"}");


            var sortedScoresWithLabel = SampleClassification.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
